import type { StoreCardProps } from '@/pages/rental/map/lib/types';

export const mockStoreList: StoreCardProps[] = [
  {
    store: { id: 1, name: 'LG유플러스 선릉점', latitude: 0, longitude: 0 },
    storeDetail: {
      storeId: 1,
      imageUrl: '',
      detailAddress: '서울 강남구 대치동',
      phoneNumber: '',
      distanceFromMe: 530,
      reviewRating: 0,
      isOpening: true,
      startTime: '10:00:00',
      endTime: '20:00:00',
    },
    deviceCount: 3,
    id: 1,
  },
  {
    store: { id: 2, name: 'LG유플러스 선릉점', latitude: 0, longitude: 0 },
    storeDetail: {
      storeId: 2,
      imageUrl: '',
      detailAddress: '서울 강남구 대치동',
      phoneNumber: '',
      distanceFromMe: 530,
      reviewRating: 0,
      isOpening: true,
      startTime: '10:00:00',
      endTime: '20:00:00',
    },
    deviceCount: 3,
    id: 2,
  },
  {
    store: { id: 3, name: 'LG유플러스 선릉점', latitude: 0, longitude: 0 },
    storeDetail: {
      storeId: 3,
      imageUrl: '',
      detailAddress: '서울 강남구 대치동',
      phoneNumber: '',
      distanceFromMe: 530,
      reviewRating: 0,
      isOpening: true,
      startTime: '10:00:00',
      endTime: '20:00:00',
    },
    deviceCount: 3,
    id: 3,
  },
  {
    store: { id: 4, name: 'LG유플러스 선릉점', latitude: 0, longitude: 0 },
    storeDetail: {
      storeId: 4,
      imageUrl: '',
      detailAddress: '서울 강남구 대치동',
      phoneNumber: '',
      distanceFromMe: 530,
      reviewRating: 0,
      isOpening: true,
      startTime: '10:00:00',
      endTime: '20:00:00',
    },
    deviceCount: 3,
    id: 4,
  },
  {
    store: { id: 5, name: 'LG유플러스 선릉점', latitude: 0, longitude: 0 },
    storeDetail: {
      storeId: 5,
      imageUrl: '',
      detailAddress: '서울 강남구 대치동',
      phoneNumber: '',
      distanceFromMe: 530,
      reviewRating: 0,
      isOpening: true,
      startTime: '10:00:00',
      endTime: '20:00:00',
    },
    deviceCount: 3,
    id: 5,
  },
  {
    store: { id: 6, name: 'LG유플러스 선릉점', latitude: 0, longitude: 0 },
    storeDetail: {
      storeId: 6,
      imageUrl: '',
      detailAddress: '서울 강남구 대치동',
      phoneNumber: '',
      distanceFromMe: 530,
      reviewRating: 0,
      isOpening: true,
      startTime: '10:00:00',
      endTime: '20:00:00',
    },
    deviceCount: 3,
    id: 6,
  },
  {
    store: { id: 7, name: 'LG유플러스 선릉점', latitude: 0, longitude: 0 },
    storeDetail: {
      storeId: 7,
      imageUrl: '',
      detailAddress: '서울 강남구 대치동',
      phoneNumber: '',
      distanceFromMe: 530,
      reviewRating: 0,
      isOpening: true,
      startTime: '10:00:00',
      endTime: '20:00:00',
    },
    deviceCount: 3,
    id: 7,
  },
];
